const productData = [
  // Móc Khóa
  {
    id: "mockhoa1",
    name: "Set Móc Khóa Toàn Chức Cao Thủ",
    img: "../Anhsp/Key/Key1.jpg",
    priceOld: "100.000VND",
    priceNew: "79.000VND",
    description: "Bộ móc khóa chủ đề Toàn Chức Cao Thủ, chất liệu acrylic cao cấp, hình ảnh sắc nét.",
    category: "mockhoa",
    rating: "4.8/5",
    sold: 120,
    stock: 35,
    ship: "30.000đ"
  },
  {
    id: "mockhoa2",
    name: "Set Móc Khóa Toàn Chức Cao Thủ",
    img: "../Anhsp/Key/Key2.jpg",
    priceOld: "100.000VND",
    priceNew: "79.000VND",
    description: "Bộ móc khóa chủ đề Toàn Chức Cao Thủ, chất liệu acrylic cao cấp, hình ảnh sắc nét.",
    category: "mockhoa",
    rating: "4.7/5",
    sold: 98,
    stock: 22,
    ship: "30.000đ"
  },
  {
    id: "mockhoa3",
    name: "Set Móc Khóa Toàn Chức Cao Thủ",
    img: "../Anhsp/Key/Key3.jpg",
    priceOld: "100.000VND",
    priceNew: "79.000VND",
    description: "Bộ móc khóa chủ đề Toàn Chức Cao Thủ, chất liệu acrylic cao cấp, hình ảnh sắc nét.",
    category: "mockhoa",
    rating: "4.8/5",
    sold: 150,
    stock: 10,
    ship: "30.000đ"
  },
  {
    id: "mockhoa4",
    name: "Set Móc Khóa Toàn Chức Cao Thủ",
    img: "../Anhsp/Key/Key4.jpg",
    priceOld: "100.000VND",
    priceNew: "79.000VND",
    description: "Bộ móc khóa chủ đề Toàn Chức Cao Thủ, chất liệu acrylic cao cấp, hình ảnh sắc nét.",
    category: "mockhoa",
    rating: "4.9/5",
    sold: 200,
    stock: 5,
    ship: "30.000đ"
  },
  // Huy Hiệu
  {
    id: "badge1",
    name: "Set Huy Hiệu Toàn Chức Cao Thủ",
    img: "../Anhsp/Badge/Bg1.jpg",
    priceOld: "380.000VND",
    priceNew: "299.999VND",
    description: "Set huy hiệu nhân vật Toàn Chức Cao Thủ, phù hợp sưu tầm và trang trí balo, áo.",
    category: "huyhieu",
    rating: "4.9/5",
    sold: 210,
    stock: 12,
    ship: "30.000đ"
  },
  {
    id: "badge2",
    name: "Set Huy Hiệu Toàn Chức Cao Thủ",
    img: "../Anhsp/Badge/Bg2.jpg",
    priceOld: "380.000VND",
    priceNew: "299.999VND",
    description: "Set huy hiệu nhân vật Toàn Chức Cao Thủ, phù hợp sưu tầm và trang trí balo, áo.",
    category: "huyhieu",
    rating: "4.8/5",
    sold: 180,
    stock: 15,
    ship: "30.000đ"
  },
  {
    id: "badge3",
    name: "Set Huy Hiệu Toàn Chức Cao Thủ",
    img: "../Anhsp/Badge/Bg5.jpg",
    priceOld: "380.000VND",
    priceNew: "299.999VND",
    description: "Set huy hiệu nhân vật Toàn Chức Cao Thủ, phù hợp sưu tầm và trang trí balo, áo.",
    category: "huyhieu",
    rating: "4.7/5",
    sold: 160,
    stock: 20,
    ship: "30.000đ"
  },
  // Card
  {
    id: "card1",
    name: "Set Card Toàn Chức Cao Thủ",
    img: "../Anhsp/Card/Pc1.jpg",
    priceOld: "70.000VND",
    priceNew: "49.000VND",
    description: "Set card nhân vật Toàn Chức Cao Thủ, chất liệu giấy cứng, hình ảnh sắc nét.",
    category: "card",
    rating: "4.5/5",
    sold: 300,
    stock: 50,
    ship: "20.000đ"
  },
  {
    id: "card2",
    name: "Set Card Toàn Chức Cao Thủ",
    img: "../Anhsp/Card/Pc2.jpg",
    priceOld: "70.000VND",
    priceNew: "49.000VND",
    description: "Set card nhân vật Toàn Chức Cao Thủ, chất liệu giấy cứng, hình ảnh sắc nét.",
    category: "card",
    rating: "4.6/5",
    sold: 280,
    stock: 45,
    ship: "20.000đ"
  },
  {
    id: "card3",
    name: "Set Card Toàn Chức Cao Thủ",
    img: "../Anhsp/Card/Pc3.jpg",
    priceOld: "70.000VND",
    priceNew: "49.000VND",
    description: "Set card nhân vật Toàn Chức Cao Thủ, chất liệu giấy cứng, hình ảnh sắc nét.",
    category: "card",
    rating: "4.7/5",
    sold: 250,
    stock: 40,
    ship: "20.000đ"
  },
  {
    id: "card4",
    name: "Set Card Toàn Chức Cao Thủ",
    img: "../Anhsp/Card/Pc4.jpg",
    priceOld: "70.000VND",
    priceNew: "49.000VND",
    description: "Set card nhân vật Toàn Chức Cao Thủ, chất liệu giấy cứng, hình ảnh sắc nét.",
    category: "card",
    rating: "4.5/5",
    sold: 310,
    stock: 55,
    ship: "20.000đ"
  },
  {
    id: "card5",
    name: "Set Card Toàn Chức Cao Thủ",
    img: "../Anhsp/Card/Pc5.jpg",
    priceOld: "70.000VND",
    priceNew: "49.000VND",
    description: "Set card nhân vật Toàn Chức Cao Thủ, chất liệu giấy cứng, hình ảnh sắc nét.",
    category: "card",
    rating: "4.6/5",
    sold: 290,
    stock: 50,
    ship: "20.000đ"
  },
  {
    id: "card6",
    name: "Set Card Toàn Chức Cao Thủ",
    img: "../Anhsp/Card/Pc6.jpg",
    priceOld: "70.000VND",
    priceNew: "49.000VND",
    description: "Set card nhân vật Toàn Chức Cao Thủ, chất liệu giấy cứng, hình ảnh sắc nét.",
    category: "card",
    rating: "4.7/5",
    sold: 260,
    stock: 35,
    ship: "20.000đ"
  },
  {
    id: "card7",
    name: "Set Card Toàn Chức Cao Thủ",
    img: "../Anhsp/Card/Pc7.jpg",
    priceOld: "70.000VND",
    priceNew: "49.000VND",
    description: "Set card nhân vật Toàn Chức Cao Thủ, chất liệu giấy cứng, hình ảnh sắc nét.",
    category: "card",
    rating: "4.5/5",
    sold: 320,
    stock: 60,
    ship: "20.000đ"
  },
  {
    id: "card8",
    name: "Set Card Toàn Chức Cao Thủ",
    img: "../Anhsp/Card/Pc8.jpg",
    priceOld: "70.000VND",
    priceNew: "49.000VND",
    description: "Set card nhân vật Toàn Chức Cao Thủ, chất liệu giấy cứng, hình ảnh sắc nét.",
    category: "card",
    rating: "4.6/5",
    sold: 300,
    stock: 55,
    ship: "20.000đ"
  },
  // Pola
  {
    id: "pola1",
    name: "Ảnh Pola Toàn Chức Cao Thủ",
    img: "../Anhsp/Pola/pola1.jpg",
    priceOld: "50.000VND",
    priceNew: "35.000VND",
    description: "Ảnh Pola chủ đề Toàn Chức Cao Thủ, chất liệu giấy ảnh cao cấp.",
    category: "pola",
    rating: "4.5/5",
    sold: 150,
    stock: 25,
    ship: "10.000đ"
  },
  {
    id: "pola2",
    name: "Ảnh Pola Toàn Chức Cao Thủ",
    img: "../Anhsp/Pola/pola2.jpg",
    priceOld: "50.000VND",
    priceNew: "35.000VND",
    description: "Ảnh Pola chủ đề Toàn Chức Cao Thủ, chất liệu giấy ảnh cao cấp.",
    category: "pola",
    rating: "4.6/5",
    sold: 130,
    stock: 20,
    ship: "10.000đ"
  },
  {
    id: "pola3",
    name: "Ảnh Pola Toàn Chức Cao Thủ",
    img: "../Anhsp/Pola/pola3.jpg",
    priceOld: "50.000VND",
    priceNew: "35.000VND",
    description: "Ảnh Pola chủ đề Toàn Chức Cao Thủ, chất liệu giấy ảnh cao cấp.",
    category: "pola",
    rating: "4.7/5",
    sold: 120,
    stock: 15,
    ship: "10.000đ"
  },
  // Ban Phím
  {
    id: "banphim1",
    name: "Bàn Phím Cơ TCC Thủ",
    img: "../Anhsp/Banphim/Kw1.jpg",
    priceOld: "1.200.000VND",
    priceNew: "999.000VND",
    description: "Bàn phím cơ chủ đề Toàn Chức Cao Thủ, switch chất lượng cao.",
    category: "banphim",
    rating: "4.8/5",
    sold: 75,
    stock: 10,
    ship: "50.000đ"
  },
  {
    id: "banphim2",
    name: "Bàn Phím Cơ TCC Thủ",
    img: "../Anhsp/Banphim/Kw2.jpg",
    priceOld: "1.200.000VND",
    priceNew: "999.000VND",
    description: "Bàn phím cơ chủ đề Toàn Chức Cao Thủ, switch chất lượng cao.",
    category: "banphim",
    rating: "4.9/5",
    sold: 85,
    stock: 8,
    ship: "50.000đ"
  },
  // Figure
  {
    id: "figure1",
    name: "Set Figure Toàn Chức Cao Thủ",
    img: "../Anhsp/Fig/Fig1.jpg",
    priceOld: "2.000.000VND",
    priceNew: "1.599.000VND",
    description: "Figure nhân vật Toàn Chức Cao Thủ, chi tiết sắc nét, chất liệu nhựa cao cấp.",
    category: "figure",
    rating: "4.9/5",
    sold: 60,
    stock: 5,
    ship: "70.000đ"
  },
  // Shikishi
  {
    id: "shikishi1",
    name: "Set Shikishi Toàn Chức Cao Thủ",
    img: "../Anhsp/Sks/Sks1.jpg",
    priceOld: "150.000VND",
    priceNew: "129.000VND",
    description: "Shikishi chủ đề Toàn Chức Cao Thủ, tranh vẽ tay trên giấy truyền thống.",
    category: "shikishi",
    rating: "4.7/5",
    sold: 110,
    stock: 20,
    ship: "15.000đ"
  },
  {
    id: "shikishi2",
    name: "Set Shikishi Toàn Chức Cao Thủ",
    img: "../Anhsp/Sks/Sks2.jpg",
    priceOld: "150.000VND",
    priceNew: "129.000VND",
    description: "Shikishi chủ đề Toàn Chức Cao Thủ, tranh vẽ tay trên giấy truyền thống.",
    category: "shikishi",
    rating: "4.8/5",
    sold: 120,
    stock: 18,
    ship: "15.000đ"
  },
  {
    id: "shikishi3",
    name: "Set Shikishi Toàn Chức Cao Thủ",
    img: "../Anhsp/Sks/Sks3.jpg",
    priceOld: "150.000VND",
    priceNew: "129.000VND",
    description: "Shikishi chủ đề Toàn Chức Cao Thủ, tranh vẽ tay trên giấy truyền thống.",
    category: "shikishi",
    rating: "4.6/5",
    sold: 100,
    stock: 25,
    ship: "15.000đ"
  },
  {
    id: "shikishi4",
    name: "Set Shikishi Toàn Chức Cao Thủ",
    img: "../Anhsp/Sks/Sks4.jpg",
    priceOld: "150.000VND",
    priceNew: "129.000VND",
    description: "Shikishi chủ đề Toàn Chức Cao Thủ, tranh vẽ tay trên giấy truyền thống.",
    category: "shikishi",
    rating: "4.7/5",
    sold: 115,
    stock: 22,
    ship: "15.000đ"
  },
  // Vé
  {
    id: "ve1",
    name: "Set Vé Toàn Chức Cao Thủ",
    img: "../Anhsp/Ve/ve1.jpg",
    priceOld: "150.000VND",
    priceNew: "99.000VND",
    description: "Vé sự kiện Toàn Chức Cao Thủ, số lượng giới hạn.",
    category: "ve",
    rating: "4.8/5",
    sold: 90,
    stock: 10,
    ship: "10.000đ"
  },
  {
    id: "ve2",
    name: "Set Vé Toàn Chức Cao Thủ",
    img: "../Anhsp/Ve/ve2.jpg",
    priceOld: "150.000VND",
    priceNew: "99.000VND",
    description: "Vé sự kiện Toàn Chức Cao Thủ, số lượng giới hạn.",
    category: "ve",
    rating: "4.9/5",
    sold: 110,
    stock: 8,
    ship: "10.000đ"
  }
];
